# Default values for installing Domino in a K8s cluster

github_access_token_pieces: default-substitute-this-for-your-own-token
github_access_token_workflows: default-substitute-this-for-your-own-token

# Frontend service
frontend:
  enabled: true
  image: ghcr.io/iisas/domino-frontend:k8s
  deployMode: local-k8s # TODO change to prod
  apiUrl: http://localhost/api
  baseName: /

# REST service
rest:
  enabled: true
  image: ghcr.io/iisas/domino-rest:latest
  tag: latest
  deployMode: local-k8s # TODO change to prod
  # Github workflows repository name - Same one used in airflow gitSync ssh
  workflowsRepository: ~
  createDefaultUser: true
  rootPath: /api

# Change this if using external Database
database:
  enabled: true
  image: postgres:13
  name: postgres
  user: postgres
  password: postgres
  port: "5432"
